#!/usr/bin/env python3
"""Print a reviewed, password-free backup role provisioner. Never connects to a DB.

Run the output as a schema owner. Set a generated SCRAM password and LOGIN only
as a separate final step; no application/service role membership is granted.
"""
import importlib.util
import pathlib

spec = importlib.util.spec_from_file_location('backup_create', pathlib.Path(__file__).with_name('create.py'))
backup = importlib.util.module_from_spec(spec)
spec.loader.exec_module(backup)
allowed = sorted([('public', table) for table in backup.PUBLIC_DATA]
                 + [('auth', table) for table in backup.AUTH_DATA]
                 + [('supabase_migrations', table) for table in backup.MIGRATION_DATA])
values = ',\n    '.join("('%s','%s')" % item for item in allowed)
print("""-- Generated by scripts/backup/provision-role.py; contains no password.
BEGIN;
DO $$BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='lecue_backup') THEN
    CREATE ROLE lecue_backup NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  END IF;
END$$;
ALTER ROLE lecue_backup NOLOGIN NOINHERIT CONNECTION LIMIT 2;
DO $$BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='lecue_backup' AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls)) THEN
    RAISE EXCEPTION 'Existing backup role has privileged attributes; refusing to use it';
  END IF;
  -- PostgreSQL 16+ grants a non-superuser creator ADMIN membership in the
  -- created role. Accept only this operator's non-inheriting, non-SET edge.
  IF EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid=m.member OR r.oid=m.roleid
    WHERE r.rolname='lecue_backup' AND NOT (
      m.roleid=r.oid AND m.member=current_user::regrole::oid AND m.admin_option
      AND NOT m.inherit_option AND NOT m.set_option
    )) THEN
    RAISE EXCEPTION 'Backup role must not have role memberships in either direction';
  END IF;
  -- Owners can restore their own revoked privileges. Reject ownership, including
  -- objects in other databases, rather than treating REVOKE as a security boundary.
  IF EXISTS (SELECT 1 FROM pg_shdepend d JOIN pg_roles r ON r.oid=d.refobjid
    WHERE d.refclassid='pg_authid'::regclass AND d.deptype='o' AND r.rolname='lecue_backup') THEN
    RAISE EXCEPTION 'Existing backup role owns database objects; refusing to use it';
  END IF;
END$$;
ALTER ROLE lecue_backup SET default_transaction_read_only = on;
ALTER ROLE lecue_backup SET statement_timeout = '15min';
ALTER ROLE lecue_backup SET lock_timeout = '30s';
ALTER ROLE lecue_backup SET idle_in_transaction_session_timeout = '15min';
REVOKE ALL ON SCHEMA public,auth,supabase_migrations FROM lecue_backup;
REVOKE ALL ON ALL TABLES IN SCHEMA public,auth,supabase_migrations FROM lecue_backup;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public,auth,supabase_migrations FROM lecue_backup;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public,auth,supabase_migrations FROM lecue_backup;
GRANT USAGE ON SCHEMA public,auth,supabase_migrations TO lecue_backup;
CREATE TEMP TABLE backup_allowed(schema_name text,table_name text,PRIMARY KEY(schema_name,table_name)) ON COMMIT DROP;
INSERT INTO backup_allowed VALUES
    """ + values + ";")
print("""
DO $$DECLARE r record; unsafe_functions text;
  write_privileges text := 'INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER';
BEGIN
  IF has_schema_privilege('lecue_backup','public','CREATE') OR has_schema_privilege('lecue_backup','auth','CREATE') OR has_schema_privilege('lecue_backup','supabase_migrations','CREATE') THEN
    RAISE EXCEPTION 'Inherited schema CREATE privilege must be removed before backup provisioning';
  END IF;
  -- NOINHERIT does not remove PUBLIC routine privileges. Refuse an executable
  -- definer routine rather than silently granting the backup login a write path.
  -- A trigger function can be attached to an owned temporary table and invoked
  -- indirectly. Only event triggers require a superuser and can be excluded.
  SELECT string_agg(n.nspname||'.'||p.proname,', ') INTO unsafe_functions
    FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname IN ('public','auth','supabase_migrations') AND p.prosecdef
      AND p.prorettype <> 'event_trigger'::regtype
      AND has_function_privilege('lecue_backup',p.oid,'EXECUTE');
  IF unsafe_functions IS NOT NULL THEN
    RAISE EXCEPTION 'Review PUBLIC definer privileges before enabling backup login: %',unsafe_functions;
  END IF;
  FOR r IN SELECT n.nspname,c.relname,string_agg(quote_ident(a.attname),',') AS columns
    FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid
    WHERE n.nspname IN ('public','auth','supabase_migrations') AND c.relkind IN ('r','p','v','m','f')
      AND a.attnum>0 AND NOT a.attisdropped GROUP BY n.nspname,c.relname
  LOOP
    -- Clear any older explicit column grants as well as relation grants.
    EXECUTE format('REVOKE SELECT (%s),INSERT (%s),UPDATE (%s),REFERENCES (%s) ON %I.%I FROM lecue_backup',r.columns,r.columns,r.columns,r.columns,r.nspname,r.relname);
  END LOOP;
  FOR r IN SELECT n.nspname,c.relname,c.relrowsecurity FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    JOIN backup_allowed a ON a.schema_name=n.nspname AND a.table_name=c.relname WHERE c.relkind IN ('r','p')
  LOOP
    EXECUTE format('GRANT SELECT ON %I.%I TO lecue_backup',r.nspname,r.relname);
    IF r.relrowsecurity THEN
      -- Add only this role's read policy. Existing app policies and RLS flags stay intact.
      EXECUTE format('DROP POLICY IF EXISTS lecue_backup_read ON %I.%I',r.nspname,r.relname);
      EXECUTE format('CREATE POLICY lecue_backup_read ON %I.%I FOR SELECT TO lecue_backup USING (true)',r.nspname,r.relname);
    END IF;
  END LOOP;
  FOR r IN SELECT ns.nspname,seq.relname FROM pg_class seq JOIN pg_namespace ns ON ns.oid=seq.relnamespace
    JOIN pg_depend d ON d.objid=seq.oid AND d.classid='pg_class'::regclass AND d.refclassid='pg_class'::regclass AND d.deptype IN ('a','i')
    JOIN pg_class t ON t.oid=d.refobjid JOIN pg_namespace tn ON tn.oid=t.relnamespace
    JOIN backup_allowed a ON a.schema_name=tn.nspname AND a.table_name=t.relname WHERE seq.relkind='S'
  LOOP
    -- SELECT reads the restore sequence value; no USAGE/UPDATE means no nextval/setval.
    EXECUTE format('GRANT SELECT ON SEQUENCE %I.%I TO lecue_backup',r.nspname,r.relname);
  END LOOP;
  -- Explicit REVOKE does not remove PUBLIC privileges. Audit the effective
  -- result and fail without changing other roles' rights or application policies.
  IF current_setting('server_version_num')::integer >= 170000 THEN
    write_privileges := write_privileges || ',MAINTAIN';
  END IF;
  FOR r IN SELECT c.oid,n.nspname,c.relname,
      (c.relkind IN ('r','p') AND a.table_name IS NOT NULL) AS allowed_read
    FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    LEFT JOIN backup_allowed a ON a.schema_name=n.nspname AND a.table_name=c.relname
    WHERE n.nspname IN ('public','auth','supabase_migrations') AND c.relkind IN ('r','p','v','m','f')
  LOOP
    IF has_table_privilege('lecue_backup',r.oid,write_privileges)
      OR has_any_column_privilege('lecue_backup',r.oid,'INSERT,UPDATE,REFERENCES') THEN
      RAISE EXCEPTION 'Backup role retains write privileges on %',format('%I.%I',r.nspname,r.relname);
    END IF;
    IF NOT r.allowed_read AND (has_table_privilege('lecue_backup',r.oid,'SELECT')
      OR has_any_column_privilege('lecue_backup',r.oid,'SELECT')) THEN
      RAISE EXCEPTION 'Backup role retains SELECT on excluded relation %',format('%I.%I',r.nspname,r.relname);
    END IF;
  END LOOP;
  FOR r IN SELECT seq.oid,ns.nspname,seq.relname,EXISTS (
      SELECT 1 FROM pg_depend d JOIN pg_class t ON t.oid=d.refobjid
      JOIN pg_namespace tn ON tn.oid=t.relnamespace
      JOIN backup_allowed a ON a.schema_name=tn.nspname AND a.table_name=t.relname
      WHERE d.objid=seq.oid AND d.classid='pg_class'::regclass AND d.refclassid='pg_class'::regclass
        AND d.deptype IN ('a','i') AND t.relkind IN ('r','p')
    ) AS allowed_read
    FROM pg_class seq JOIN pg_namespace ns ON ns.oid=seq.relnamespace
    WHERE seq.relkind='S' AND ns.nspname IN ('public','auth','supabase_migrations')
  LOOP
    IF has_sequence_privilege('lecue_backup',r.oid,'USAGE,UPDATE') THEN
      RAISE EXCEPTION 'Backup role retains sequence USAGE or UPDATE on %',format('%I.%I',r.nspname,r.relname);
    END IF;
    IF NOT r.allowed_read AND has_sequence_privilege('lecue_backup',r.oid,'SELECT') THEN
      RAISE EXCEPTION 'Backup role retains SELECT on excluded sequence %',format('%I.%I',r.nspname,r.relname);
    END IF;
  END LOOP;
END$$;
COMMIT;
-- Root/operator final step: set a generated SCRAM verifier, then ALTER ROLE lecue_backup LOGIN.
-- Keep the actual password only in the private backup repository's encrypted secret.
""")
